services:
  fastapi-app:
    build: .
    container_name: mytopo
    ports:
      - "${APP_PORT:-5000}:5000"
    environment:
      - DEBUG=False
      - N_RANGE=25-40
      - E_RANGE=43-64
#      - APP_PORT=5000
#      - APP_HOST=0.0.0.0
#      - MAX_POINTS_COUNT=1000000
#      - DATA_DIR=/datasets
#      - DATASET_FOLDER_NAME=sews-data
    volumes:
      - ./datasets:/datasets
    networks:
      - kian

networks:
  kian:
    external: true